apiVersion: v2
name: alerta
description: Helm chart to deploy Alerta and it's related resources
type: application
version: 0.1.1
appVersion: 7.4.6
home: https://github.com/alerta/alerta
maintainers:
  - name: henrycook
    email: henryjycook@gmail.com

dependencies:
  - name: postgresql
    version: 8.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: 7.10.10
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
